import { expect, test } from "bun:test"
import { createInputDraftBlobStore, MemoryInputDraftBlobDriver, type InputDraftBlobStore } from "@/sync/input-draft-blob-store"
import { draftRootAttachmentOccurrenceRefID } from "@/sync/input-draft-types"
import { LEGACY_MESSAGE_QUEUE_KEY, MESSAGE_QUEUE_LEDGER_KEY, queueLedgerScopeKey, serializeQueueLedgerSnapshot, type QueueLedgerMetadataSink } from "./message-queue-ledger"
import { migrateLegacyMessageQueue } from "./message-queue-migration"

const bound = { state: "bound" as const, transportIdentity: "runtime", directory: "/project", sessionID: "session" }
const attachment = (extra: Record<string, unknown> = {}) => ({ id: "file", dataUrl: "data:text/plain;base64,eA==", mimeType: "wrong/type", filename: "file.txt", size: 99, source: "local", ...extra })
const row = (extra: Record<string, unknown> = {}) => ({ content: "hello", owner: bound, attachments: [], ...extra })
const fixture = (queuedMessages: Record<string, unknown>) => JSON.stringify({ state: { queuedMessages } })
const sink = (legacy: string | null, ledger: string | null = null, failures: Partial<Record<"read" | "write" | "remove", "unavailable" | "quota">> = {}) => { const values = new Map<string, string | null>([[LEGACY_MESSAGE_QUEUE_KEY, legacy], [MESSAGE_QUEUE_LEDGER_KEY, ledger]]), removed: string[] = []; const target: QueueLedgerMetadataSink = { read: async (key) => failures.read ? { ok: false, error: { code: failures.read } } : { ok: true, value: values.get(key) ?? null }, write: async (key, value) => failures.write ? { ok: false, error: { code: failures.write } } : (values.set(key, value), { ok: true, value: undefined }), remove: async (key) => failures.remove ? { ok: false, error: { code: failures.remove } } : (values.delete(key), removed.push(key), { ok: true, value: undefined }) }; return { target, values, removed } }
const blobs = () => createInputDraftBlobStore(new MemoryInputDraftBlobDriver())
const item = (result: Awaited<ReturnType<typeof migrateLegacyMessageQueue>>, scope = queueLedgerScopeKey(bound)) => { expect(result.status === "committed" || result.status === "degraded").toBe(true); return (result as Extract<typeof result, { snapshot: unknown }>).snapshot.queues[scope]![0]! }

test("migrates bound local data URLs with legacy id and decoded blob metadata", async () => { const store = blobs(), result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ attachments: [attachment()] })] })).target, store), value = item(result), file = value.attachments[0]!; expect(file.attachmentID).toBe("file"); expect(file.mimeType).toBe("text/plain;charset=utf-8"); expect(file.size).toBe(1); expect(file.locator.kind).toBe("blob"); if (file.locator.kind === "blob") expect((await store.read(file.locator.blobID)).ok).toBe(true) })
test("preserves VS Code metadata and server file URL locators", async () => { const result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ attachments: [attachment({ id: "vs", source: "vscode", vscodePath: "/x", vscodeSource: "selection" }), attachment({ id: "server", source: "server", serverPath: "/srv/x", dataUrl: "file:///srv/x" })] })] })).target, blobs()), value = item(result); expect(value.attachments[0]?.source).toBe("vscode"); expect(value.attachments[0]?.vscodePath).toBe("/x"); expect(value.attachments[0]?.vscodeSource).toBe("selection"); expect(value.attachments[1]?.locator).toEqual({ kind: "url", url: "file:///srv/x" }) })
test("uses physical encoded scopes and preserves unbound data as an issue", async () => { const key = 'unbound-legacy:["old"]', result = await migrateLegacyMessageQueue(sink(fixture({ [key]: [{ content: "x", status: "sending", attachments: [attachment()] }] })).target, blobs()), value = item(result, key); expect(value.owner).toEqual({ state: "unbound-legacy", sessionID: "old" }); expect(value.status).toBe("unresolved"); expect(value.attachmentIssues[0]?.reason).toBe("legacy-unbound-data"); expect(value.failureKind).toBe(undefined); expect(serializeQueueLedgerSnapshot((result as Extract<typeof result, { snapshot: unknown }>).snapshot).ok).toBe(true) })
test("degrades owner conflicts and preserves legacy raw", async () => { const source = sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ owner: { ...bound, sessionID: "other" } })] })), result = await migrateLegacyMessageQueue(source.target, blobs()); expect(result.status).toBe("degraded"); expect(result.issues[0]?.reason).toBe("owner-conflict"); expect(source.values.get(LEGACY_MESSAGE_QUEUE_KEY)).not.toBeNull() })
test("normalizes bound and unbound dispatch states plus retry state", async () => { const result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ status: "sending" }), row({ status: "retrying", nextAttemptAt: 4 })], old: [{ content: "x", status: "sending", attachments: [] }] })).target, blobs()), boundItems = (result as Extract<typeof result, { snapshot: unknown }>).snapshot.queues[queueLedgerScopeKey(bound)]!, unbound = (result as Extract<typeof result, { snapshot: unknown }>).snapshot.queues['unbound-legacy:["old"]']![0]!; expect(boundItems[0]?.status).toBe("reconciling"); expect(boundItems[1]?.status).toBe("retrying"); expect(boundItems[1]?.nextAttemptAt).toBe(4); expect(boundItems[1]?.failureKind).toBe("pre-dispatch"); expect(unbound.status).toBe("unresolved"); expect(unbound.failureKind).toBe("ambiguous-dispatch") })
test("preserves send configuration, failure semantics, and reconciliation scheduling", async () => { const result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ status: "reconciling", sendConfig: { providerID: "p", modelID: "m", agent: "a", variant: "v" }, reconciliationStartedAt: 2, reconciliationDeadlineAt: 5, reconciliationNextCheckAt: 3 })] })).target, blobs()), value = item(result); expect(value.sendConfig).toEqual({ providerID: "p", modelID: "m", agent: "a", variant: "v" }); expect(value.failureKind).toBe("ambiguous-dispatch"); expect(value.reconciliationNextCheckAt).toBe(3) })
test("degrades overflowing reconciliation deadline fallbacks while retaining legacy raw", async () => { for (const status of ["sending", "reconciling"]) { const source = sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ status, createdAt: Number.MAX_SAFE_INTEGER - 29_999 })] })), result = await migrateLegacyMessageQueue(source.target, blobs()), value = item(result); expect(result.status).toBe("degraded"); expect(result.issues.some((entry) => entry.path.endsWith("reconciliationDeadlineAt") && entry.reason === "reconciliation-deadline-overflow")).toBe(true); expect(Number.isSafeInteger(value.reconciliationDeadlineAt)).toBe(true); expect(value.reconciliationDeadlineAt).toBeGreaterThanOrEqual(value.reconciliationStartedAt!); expect(serializeQueueLedgerSnapshot((result as Extract<typeof result, { snapshot: unknown }>).snapshot).ok).toBe(true); expect(source.values.get(LEGACY_MESSAGE_QUEUE_KEY)).not.toBeNull() } })
test("uses stable SHA fallback IDs and degrades duplicate explicit IDs", async () => { const first = await migrateLegacyMessageQueue(sink(fixture({ a: [row({ owner: undefined })] })).target, blobs()), second = await migrateLegacyMessageQueue(sink(fixture({ a: [row({ owner: undefined })] })).target, blobs()); expect(item(first, 'unbound-legacy:["a"]').queueItemID).toBe(item(second, 'unbound-legacy:["a"]').queueItemID); const duplicate = await migrateLegacyMessageQueue(sink(fixture({ a: [row({ owner: undefined, id: "same" }), row({ owner: undefined, id: "same" })] })).target, blobs()); expect(duplicate.status).toBe("degraded"); expect(duplicate.issues.some((entry) => entry.reason === "duplicate-id")).toBe(true) })
test("returns complete v4 unchanged and flags partial or corrupt v4 for recovery", async () => { const full = JSON.stringify({ version: 4, queues: {}, migration: { v3State: "complete" } }); expect((await migrateLegacyMessageQueue(sink(fixture({ a: [] }), full).target, blobs())).status).toBe("committed"); const partial = JSON.stringify({ version: 4, queues: { x: [{}] }, migration: { v3State: "complete" } }); expect((await migrateLegacyMessageQueue(sink(fixture({ a: [] }), partial).target, blobs())).status).toBe("recovery-required"); expect((await migrateLegacyMessageQueue(sink(fixture({ a: [] }), "{").target, blobs())).status).toBe("recovery-required") })
test("repairs a matching reference whose blob is missing and serializes v4", async () => { const base = blobs(), blobID = await (async () => { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode("q:file")); return `legacy-blob-${[...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("")}` })(), reads: string[] = [], store: InputDraftBlobStore = { ...base, readReference: async () => ({ ok: true, value: blobID }), putAndRetain: async (reference, actualBlobID, value) => { reads.push(actualBlobID); expect((await base.read(actualBlobID)).ok).toBe(false); return base.putAndRetain(reference, actualBlobID, value) } }, result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ id: "q", attachments: [attachment()] })] })).target, store), value = item(result); expect(reads).toEqual([blobID]); expect(value.attachments[0]?.locator).toEqual({ kind: "blob", blobID }); expect((await base.read(blobID)).ok).toBe(true); expect(serializeQueueLedgerSnapshot((result as Extract<typeof result, { snapshot: unknown }>).snapshot).ok).toBe(true) })
test("fails safely when a preexisting queue reference names another blob", async () => { const store = blobs(), reference = { transportIdentity: "runtime", owner: { kind: "queue" as const, ownerID: "q" }, attachmentOccurrenceRefID: draftRootAttachmentOccurrenceRefID("file") }; await store.putAndRetain(reference, "other", new Blob(["x"], { type: "text/plain" })); const result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ id: "q", attachments: [attachment()] })] })).target, store); expect(result.status).toBe("failed"); expect(await store.readReference(reference)).toEqual({ ok: true, value: "other" }) })
test("rolls back the first retained attachment when the second retain fails", async () => { const base = blobs(); let retains = 0; const store: InputDraftBlobStore = { ...base, putAndRetain: async (...args) => ++retains === 2 ? { ok: false, error: { code: "quota-exceeded" } } : base.putAndRetain(...args) }, result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ id: "q", attachments: [attachment({ id: "one" }), attachment({ id: "two" })] })] })).target, store), reference = await base.readReference({ transportIdentity: "runtime", owner: { kind: "queue", ownerID: "q" }, attachmentOccurrenceRefID: draftRootAttachmentOccurrenceRefID("one") }); expect(result.status).toBe("failed"); expect(reference).toEqual({ ok: true, value: undefined }) })
test("records rollback release failure while preserving legacy raw", async () => { const base = blobs(), source = sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ attachments: [attachment()] })] }), null, { write: "quota" }), store: InputDraftBlobStore = { ...base, releaseIfMatches: async () => ({ ok: false, error: { code: "transaction-failed" } }) }, result = await migrateLegacyMessageQueue(source.target, store); expect(result.status).toBe("failed"); expect(result.cleanupErrors[0]?.reason).toBe("rollback-transaction-failed"); expect(source.values.get(LEGACY_MESSAGE_QUEUE_KEY)).not.toBeNull() })
test("records malformed and oversized data as attachment issues while retaining valid rows", async () => { const huge = `data:text/plain,${"x".repeat(25 * 1024 * 1024 + 1)}`, result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ attachments: [attachment({ id: "bad", dataUrl: "data:text/plain;base64,%" })] }), row({ attachments: [attachment({ id: "huge", dataUrl: huge })] }), row()] })).target, blobs()); expect(result.status).toBe("degraded"); const values = (result as Extract<typeof result, { snapshot: unknown }>).snapshot.queues[queueLedgerScopeKey(bound)]!; expect(values).toHaveLength(3); expect(values[0]?.attachmentIssues[0]?.reason).toBe("legacy-bytes-missing"); expect(values[2]?.content).toBe("hello") })
test("degrades duplicate attachment occurrences while retaining only the first blob", async () => { const base = blobs(); let reads = 0, retains = 0; const store: InputDraftBlobStore = { ...base, readReference: async (...args) => { reads++; return base.readReference(...args) }, putAndRetain: async (...args) => { retains++; return base.putAndRetain(...args) } }, source = sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ attachments: [attachment({ id: "duplicate" }), attachment({ id: "duplicate" })] })] })), result = await migrateLegacyMessageQueue(source.target, store), value = item(result); expect(result.status).toBe("degraded"); expect(result.issues.some((entry) => entry.reason === "duplicate-attachment-occurrence")).toBe(true); expect(value.attachments).toHaveLength(1); expect(reads).toBe(1); expect(retains).toBe(1); expect(source.values.get(LEGACY_MESSAGE_QUEUE_KEY)).not.toBeNull(); expect(serializeQueueLedgerSnapshot((result as Extract<typeof result, { snapshot: unknown }>).snapshot).ok).toBe(true) })
test("retains valid rows when one legacy row is corrupt", async () => { const result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [null, row()] })).target, blobs()); expect(result.status).toBe("degraded"); expect(item(result).content).toBe("hello"); expect(result.issues[0]?.reason).toBe("legacy-item") })
test("keeps degraded raw, removes complete raw, and reports remove failure", async () => { const degraded = sink(fixture({ bad: {} })), complete = sink(fixture({ a: [{ content: "x", attachments: [] }] })), removal = sink(fixture({ a: [{ content: "x", attachments: [] }] }), null, { remove: "unavailable" }); const completeResult = await migrateLegacyMessageQueue(complete.target, blobs()); await migrateLegacyMessageQueue(degraded.target, blobs()); const result = await migrateLegacyMessageQueue(removal.target, blobs()); expect(degraded.values.get(LEGACY_MESSAGE_QUEUE_KEY)).not.toBeNull(); expect(completeResult.issues).toEqual([]); expect(completeResult.status).toBe("committed"); expect(complete.values.has(LEGACY_MESSAGE_QUEUE_KEY)).toBe(false); expect(result.status).toBe("committed"); expect(result.cleanupErrors).toHaveLength(1) })
test("keeps legacy unresolved terminal semantics serializable", async () => { const result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ status: "unresolved" }), row({ status: "unresolved", attachments: [attachment({ dataUrl: "blob:lost" })] })] })).target, blobs()), values = (result as Extract<typeof result, { snapshot: unknown }>).snapshot.queues[queueLedgerScopeKey(bound)]!; expect(values[0]?.failureKind).toBe("ambiguous-dispatch"); expect(values[0]?.reconciliationChecks).toBeDefined(); expect(values[1]?.attachmentIssues).toHaveLength(1); expect(values[1]?.failureKind).toBe(undefined); expect(serializeQueueLedgerSnapshot((result as Extract<typeof result, { snapshot: unknown }>).snapshot).ok).toBe(true) })
test("normalizes legacy failure kind fields", async () => { const result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ failure: { kind: "pre-dispatch" } }), row({ failureKind: "ambiguous-dispatch" }), row({ failure: { kind: "definitive" } })] })).target, blobs()), values = (result as Extract<typeof result, { snapshot: unknown }>).snapshot.queues[queueLedgerScopeKey(bound)]!; expect(values.map((value) => value.status)).toEqual(["retrying", "reconciling", "failed"]); expect(values.map((value) => value.failureKind)).toEqual(["pre-dispatch", "ambiguous-dispatch", "definitive"]) })
test("turns malformed attachment source metadata into serializable attachment issues", async () => { const result = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ attachments: [attachment({ id: "server", source: "server" }), attachment({ id: "vscode-path", source: "vscode", vscodePath: "/x" }), attachment({ id: "vscode-cross", source: "vscode", vscodePath: "/x", vscodeSource: "file", serverPath: "/srv" }), attachment({ id: "unknown", source: "unknown" })] })] })).target, blobs()), value = item(result); expect(result.status).toBe("degraded"); expect(value.status).toBe("unresolved"); expect(value.attachmentIssues).toHaveLength(4); expect(serializeQueueLedgerSnapshot((result as Extract<typeof result, { snapshot: unknown }>).snapshot).ok).toBe(true) })
test("bounds scopes, items, and blob migration work", async () => { const scopes = Object.fromEntries(Array.from({ length: 129 }, (_, index) => [`scope-${index}`, [row({ owner: undefined })]])), scopeResult = await migrateLegacyMessageQueue(sink(fixture(scopes)).target, blobs()); expect(scopeResult.status).toBe("degraded"); expect(Object.keys((scopeResult as Extract<typeof scopeResult, { snapshot: unknown }>).snapshot.queues)).toHaveLength(128); const items = Array.from({ length: 2049 }, () => row()), itemResult = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: items })).target, blobs()); expect((itemResult as Extract<typeof itemResult, { snapshot: unknown }>).snapshot.queues[queueLedgerScopeKey(bound)]).toHaveLength(2048); let retains = 0; const base = blobs(), store: InputDraftBlobStore = { ...base, putAndRetain: async (...args) => { retains++; return base.putAndRetain(...args) } }, attachments = Array.from({ length: 65 }, (_, index) => attachment({ id: `file-${index}` })), attachmentResult = await migrateLegacyMessageQueue(sink(fixture({ [queueLedgerScopeKey(bound)]: [row({ attachments })] })).target, store), attachmentValue = item(attachmentResult); expect(attachmentValue.attachments).toHaveLength(64); expect(retains).toBe(64) })
test("returns existing degraded v4 as degraded with its legacy raw intact", async () => { const legacy = fixture({ a: [] }), existing = JSON.stringify({ version: 4, queues: {}, migration: { v3State: "degraded" } }), source = sink(legacy, existing), result = await migrateLegacyMessageQueue(source.target, blobs()); expect(result.status).toBe("degraded"); expect(result.issues[0]?.reason).toBe("existing-degraded"); expect(source.values.get(LEGACY_MESSAGE_QUEUE_KEY)).toBe(legacy) })
